/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "xy-black-primary": "#121212",
        "xy-black-secondary": "#1b1b1b",
        "xy-black-tertiary": "#0a0a0a",
        "xy-white": "#f7f7f8",
        "xy-white-transparent": "#ffffff20",
        "xy-grey-faded": "#3b3b3b",
        "xy-greyed-out": "#6b6b73",
        "xy-muted": "#aca8ae",
        "xy-green-accent": "#7de486",
        "xy-green-lightest-transparent": "#7de48620",
        "xy-green-mid-transparent": "#7de48635",
        "xy-green-darkest-transparent": "#7de48650",
        "xy-green-darker-transparent": "#7de48625",
        "xy-blue-lighter": "#85b8ff",
        "xy-blue-darker": "#2f81f7",
        "xy-bold-blue": "#4cc2fb",
        "xy-deep-blue": "#4788CC",
        "xy-baby-blue": "#9cdcfe",
        "xy-red-pastel": "#FF5858",
        "xy-neon-green": "#22c942",
        "xy-green": "#6A9955",
        "xy-light-green": "#B4CDA8",
        "xy-yellow": "#FFFF00",
        "xy-light-yellow": "#DCDCAA",
        "xy-purple": "#c678dd",
        "xy-orange": "#CD9069",
        "xy-light-neon-green": "#7ce184",
        "xy-cyan": "#08e7c5",
      },
    },
  },
  plugins: [],
};
